unstable_features = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
force_multiline_blocks = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
combine_control_expr = false
condense_wildcard_suffixes = true
fn_single_line = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true