[package]
name = "qinetic_window"
version = "0.1.2"
authors = [
	"Vladislav Loginov <vl.mr.freeman@gmail.com>",
]
edition = "2021"
description = "crate for Qinetic, containing window functionality"
documentation = "https://docs.rs/qinetic_window"
readme = "README.md"
repository = "https://github.com/vl-mr-freeman/qinetic"
license = "MIT"
keywords = ["qinetic"]

[features]
wayland = ["winit/wayland"]
x11 = ["winit/x11"]

default = [
	"wayland"
]

[dependencies]
qinetic_app = { path = "../app", version = "0.*" }
qinetic_ecs = { path = "../ecs", version = "0.* "}

winit = { version = "0.27", default-features = false }
